---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vfrfi-cots
  name: vfrfi-cots
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: vfrfi-cots
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vfrfi-cots-deployment
  labels:
    app: vfrfi-cots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vfrfi-cots
  template:
    metadata:
      labels:
        app: vfrfi-cots
    spec:
      containers:
      - name: vfrfi-cots
        image: harbor.berkeley.cf-app.com/library/vendor-app-trusted:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
