---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: cf-demos
- name: app-info

run:
  path: cf-demos/blue-green/ci/switch-routes.sh
