---
resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.15"

- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: vendor-app-external
  type: docker-image
  check_every: 10s
  source:
    repository: billglover/cots-application

- name: vendor-app-internal
  type: docker-image
  source:
    repository: harbor.berkeley.cf-app.com:443/library/cots-application-internal
    username: {{docker-username}}
    password: {{docker-password}}
    insecure_registries:
    - harbor.berkeley.cf-app.com:443

- name: deployment-config
  type: git
  check_every: 10s
  source:
    branch: master
    uri: https://github.com/billglover/cf-demos
    paths: [concourse-k8s/*]

- name: pks-test
  type: kubernetes
  source:
    server: https://cluster-1.berkeley.cf-app.com:8443
    namespace: test
    token: {{cluster_token}}
    certificate_authority: {{cluster_ca_cert}}

- name: pks-prod
  type: kubernetes
  source:
    server: https://cluster-1.berkeley.cf-app.com:8443
    namespace: prod
    token: {{cluster_token}}
    certificate_authority: {{cluster_ca_cert}}

- name: health-check
  type: file-url
  source:
    url: http://35.189.214.71/
    filename: response

jobs:
- name: push-vendor-internal
  plan:
  - get: vendor-app-external
    trigger: true
    params:
      save: true
  - put: vendor-app-internal
    params:
      load: vendor-app-external

- name: deploy-to-test
  plan:
  - aggregate:
    - get: deployment-config
      trigger: true
    - get: vendor-app-internal
      passed: [push-vendor-internal]
  - put: pks-test
    params:
      kubectl: apply -f cf-demos/concourse-k8s/deployment/cots-application.yml
      wait_until_ready_selector: app=nginx

- name: test
  plan:
  - get: vendor-app-internal
    passed: [deploy-to-test]
  - get: health-check

- name: deploy-to-prod
  plan:
  - get: deployment-config
  - get: vendor-app-internal
    passed: [test]
  - put: pks-prod
    params:
      kubectl: apply -f cf-demos/concourse-k8s/deployment/cots-application.yml
      wait_until_ready_selector: app=nginx
